$(document).ready(function(){
    $("#baidu").click(function(){
        window.location.href="http://www.baidu.com";
    });
    $("#google").click(function(){
        window.location.href="http://www.google.com";
    });
    $("#translate").click(function(){
        window.location.href="https://translate.google.cn";
    });
    $("#leetcode").click(function(){
        window.location.href="https://leetcode-cn.com/";
    });
    $("#csdn").click(function(){
        window.location.href="https://blog.csdn.net/wangerxiao121223";
    });
    $("#leetcode").click(function(){
        window.location.href="https://leetcode-cn.com/";
    });
    $("#blog").click(function(){
        window.location.href="https://www.cnblogs.com/melodyjerry/";
    });
    $("#github").click(function(){
        window.location.href="https://github.com";
    });
    $("#bilibili").click(function(){
        window.location.href="https://www.bilibili.com";
    });
    $("#youtube").click(function(){
        window.location.href="https://www.youtube.com";
    });
    $("#qqemail").click(function(){
        window.location.href="https://mail.qq.com";
    });
    $("#wyy").click(function(){
        window.location.href="https://music.163.com/";
    });

    
    $("#ysxw").click(function(){
        window.location.href="https://tv.cctv.com/live/cctv13/";
    });
    $("#ysw").click(function(){
        window.location.href="https://news.cctv.com/china/";
    });
    $("#dszb").click(function(){
        window.location.href="https://tv.cctv.com/live/cctv10/?spm=C28340.PEhBjB4gO3ob.ExidtyEJcS5K.11";
    });
    $("#jrtt").click(function(){
        window.location.href="https://www.toutiao.com/";
    });
    $("#jkys").click(function(){
        window.location.href="https://laoling.cctv.com/jk/index.shtml?spm=C78478.P2K2EYwEoH1M.MZLIXF53zVBk.4";
    });
    $("#yinshi").click(function(){
        window.location.href="https://culture-travel.cctv.com/?spm=C78478.P2K2EYwEoH1M.Ewq1d7wTU5C6.5";
    });
    $("#dianhua").click(function(){
        window.location.href="https://baijiahao.baidu.com/s?id=1724933333683412737&wfr=spider&for=pc";
    });
    $("#shuhua").click(function(){
        window.location.href="https://arts.cctv.com/?spm=C78478.P2K2EYwEoH1M.Ewq1d7wTU5C6.9";
    });
    $("#douyin").click(function(){
        window.location.href="https://www.douyin.com/";
    });
    $("#gaode").click(function(){
        window.location.href="https://gaode.com/";
    });
    $("#lvxing").click(function(){
        window.location.href="https://you.ctrip.com/globalsearch/?keyword=%E5%9B%BD%E5%86%85";
    });
    $("#shige").click(function(){
        window.location.href="https://www.gushiwen.cn/gushi/";
    });
    $("#huaniao").click(function(){
        window.location.href="http://www.huaniaowang.com/";
    });
    $("#").click(function(){
        window.location.href="";
    });
    $("#").click(function(){
        window.location.href="";
    });
    $("#").click(function(){
        window.location.href="";
    });




    
})